### ISSUE TITLE
Horizontal scroll at certain widths in demo site

### ISSUE THREAD

**Issue by msutherl** [urbit/indigo#17]
Running the demo site using `gulp site` in Chrome 73, I get some horizontal scrolling behavior at certain widths.

![indigo](https://user-images.githubusercontent.com/31774/55840853-ccb3fd00-5ae1-11e9-90cf-9303dda5dcde.gif)

**Comment by jyng** [comment]
I haven't been able to reproduce this. When you get the chance, can you inspect element on it?

**Comment by msutherl** [comment]
@jyng it might be related to https://github.com/urbit/urbit.org/issues/59

**Comment by msutherl** [comment]
Probably safe to leave this be for now and we can re-test when current updates are done.
