### ISSUE TITLE
Using the .600, .semibold classes but not being applied

### ISSUE THREAD

**Issue by friederjanmoerman** [urbit/indigo#21]
Previously the class `.text-600` class was being used, I wanted to swap it out for the `.600`, `.semibold` class but it didn't get applied, not even when I copy pasted the lines in my custom styling.

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); **they cannot start with a digit**, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".

Source: 
https://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors
https://www.w3.org/TR/CSS21/syndata.html#characters
You can check your css for errors here: http://csslint.net/

**Classes cannot start with a digit.** So I would suggest go back to the `.text-600` class or plainly `.semibold`. I will temporarily use `.text-600` in the custom css of the urbit site.

**Comment by jyng** [comment]
@friederjanmoerman Hello, just fixed this on master
