### ISSUE TITLE
some elements without classes don't get styled by indigo

### ISSUE THREAD

**Issue by friederjanmoerman** [urbit/indigo#22]
As the markdown files get converted to html in the zola port of urbit.org, the article html tags don't get classes. To style them following the indigo stylesheet rules, I would suggest putting the element itself as selector too, not just classes.

For example:
```
.P,
.t6 {
  font-size: 4rem;
  line-height: 6rem;
  font-weight: 400;
}
```

Would become:
```
p, 
.P, 
t6 {
  font-size: 4rem;
  line-height: 6rem;
  font-weight: 400;
}
```

PS: Why are the selectors on a separate line and why is the .P class written with a capital letter?

**Comment by jyng** [comment]
That's a good suggestion I had thought about. I think we tried to keep the markup and styling as separate as possible to avoid cascading hell. We prioritize Indigo around interface prototyping over marketing design. We solve this by using '.markdown' class (`indigo/src/utilities/_typography.scss`). 
Example:
```
<div class="markdown">
<h1 class=".H1"></h1>
<p class=".P"></p>
</div>

```

On capitalization, I was also wondering the same thing yesterday(albeit a bit frustrated). I found out that its to prevent collision with`.h2: height: 2rem`, so we solve it with capitalization.

**Comment by jyng** [comment]
Oops forgot about why selectors are on separate line: mostly an aesthetic choice. It promotes scanability and organization. If you're worried about file size, we minify everything and output it on file change.

**Comment by friederjanmoerman** [comment]
The problem is the docs and posts in urbit.org are built by the static site generator. The tags are generated without classes, so they do not get styled by the lines you wrote in indigo.

**Comment by jyng** [comment]
I'm about the update the typography so that it'll include selectors. All you would need to do it insert the `.markdown` class as the containing parent.
