### ISSUE TITLE
fallback fonts

### ISSUE THREAD

**Issue by shrugs** [urbit/indigo#28]
Should we allow fallback fonts to Helvetica (Neue?) and sans-serif just in case Inter isn't available?

https://github.com/urbit/indigo/blob/master/indigo/css/src/utilities/_typography.scss#L2

**Comment by shrugs** [comment]
looks like there might be some clash between Inter &  Inter UI as well: https://github.com/urbit/indigo/blob/master/indigo/css/src/utilities/_typography.scss#L288

**Comment by shrugs** [comment]
oops, found the fallbacks: https://github.com/urbit/indigo/blob/master/indigo/css/src/utilities/_typography.scss#L291

how should these be used? `<div class="inter sans"></div>` ?

**Comment by jyng** [comment]
`.inter` and `.sans` are duplicates of each other — just trying to provide options for the developer. `.sys` is a fallback stack, but I can see this being merged into `.inter` as it's common practice.

**Comment by Fang-** [comment]
> .inter and .sans are duplicates of each other — just trying to provide options for the developer. 

I'm yelling this from the sidelines, so take this with some salt, but: that doesn't seem very friendly towards the developer. Don't make them think about this! (And `.sans` seems nicer because it lets you swap out the fonts without changing the class name. It's more semantic.)

**Comment by shrugs** [comment]
definitely would include them as a fallback on `.inter`, likewise fallbacks for `.mono` to common monospaced fonts

**Comment by jyng** [comment]
@Fang- I try to keep the process on indigo as iterative as possible, so providing options is meant to discover which is more palatable. Sounds like `.sans` is a good contender. 

@shrugs Lets include those fallbacks for `.sans` and `.mono`

**Comment by shrugs** [comment]
including in #32
