### ISSUE TITLE
width: #fr has no effect

### ISSUE THREAD

**Issue by shrugs** [urbit/indigo#33]
https://github.com/urbit/indigo/blob/master/indigo/css/src/utilities/_grids.scss#L95

what's the purpose of the `.fr#` selector? if it's to set grid item freespace, I don't think `width` works, based on a scan of https://css-tricks.com/snippets/css/complete-guide-grid/

**Comment by jyng** [comment]
Hm, I didn't write this code, so my assumption here is that it's supposed to support things that might fall out of the grid say something with `display: fixed`. @g-a-v-i-n do you know what this was for?

**Comment by g-a-v-i-n** [comment]
It was an experiment that didn't work, should prob be removed

**Comment by shrugs** [comment]
included in #32
