### ISSUE TITLE
line-height & figma discrepancy

### ISSUE THREAD

**Issue by shrugs** [urbit/indigo#34]
in figma we're using a `line-height: 2;` as part of form input components — should `2` be the value of `lh-tall`?

**Comment by jyng** [comment]
<img width="1168" alt="Screen Shot 2019-06-19 at 10 29 02 AM" src="https://user-images.githubusercontent.com/9557907/59786859-13119f00-927d-11e9-91d4-75159e1b9c30.png">
Which screen does this exist? It's looking like `.lh-regular` for me.

**Comment by shrugs** [comment]
weird that I can't link to a specific figma selection, but I was referencing this one:

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/1535001/59792935-2ecf7200-928a-11e9-8b33-905a618e43bd.png">

**Comment by shrugs** [comment]
in this frame: https://www.figma.com/file/LwqBBnfmBrwuYJ75pEZcx4ey/Multipass?node-id=272%3A2660

**Comment by jyng** [comment]
Ah okay. That should have a 16px line height(`.lh-short`). I've changed & published this in Figma.
